version: "3.9"
   
services:
  db:
    image: postgis/postgis
    volumes:
        - ./data/db:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 25432:25432
    restart: on-failure

  
  web:
    build: .
    command: python manage.py runserver 0:8000
    volumes:
      - .:/mapproj
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
